name: QRadar Rule Sync

on:
  push:
    paths:
      - 'rules/**'
      - 'scripts/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # v3-dən v4-ə keçdik

      - name: Set up Python
        uses: actions/setup-python@v5  # v4-dən v5-ə keçdik
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run sync script
        run: python scripts/sync.py
